config/routes.rb
Rails.application.routes.draw do
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get 'login', to: 'pages#login', as: :new_user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: "pages#index"
  get "/profile", to: "pages#profile", as: :profile
  get "/register", to: "pages#register", as: :register
  get "/confirm/:confirmation_token", to: "pages#confirm", as: :confirm
  get "/resend_confirmation", to: "pages#resend_confirmation", as: :resend_confirmation

  resources :patients
  resources :establishments
  resources :survey_answers, only: [:index, :show, :destroy]

  draw :administration
  draw :api
end

app/models/survey_answer.rb
class SurveyAnswer < ApplicationRecord
  belongs_to :survey
  belongs_to :user

  has_many :survey_question_answers, dependent: :delete_all

  validates :date_answered, presence: true

  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      self.date_answered = Date.today
    end
  end
end

app/controllers/api/v1/survey_answers_controller.rb
module Api
  module V1
    class SurveyAnswersController < ApplicationController
      before_action :authenticate_user!

      def create
        survey  = Survey.find(params[:survey_id])

        survey_answer = ::SurveyAnswers::Create.new(
                          user: current_user,
                          survey: survey
                        ).execute!

        render json: { id: survey_answer.id }
      end

      def submit_answer
        survey_question_answer  = SurveyQuestionAnswer.find(params[:id])
        answer                  = params[:answer]

        survey_question_answer.update!(answer: answer)

        render json: { message: "ok" }
      end

      def finalize
        survey_answer = SurveyAnswer.find(params[:id])
        answers       = JSON.parse(params[:answers])
        
        answers.each do |a|
          survey_answer.survey_question_answers.where(
            id: a["id"]
          ).first.update!(answer: a["answer"])
        end

        survey_answer.update!(is_final: true, date_submitted: Date.today)

        render json: { message: "ok" }
      end
    end
  end
end

app/controllers/survey_answers_controller.rb
class SurveyAnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_active!
  before_action :load_survey_answer, only: [:destroy, :show]

  def index
    @survey_answers = SurveyAnswer.where(
                        user_id: current_user.id
                      ).order("updated_at DESC")

    @survey_answers = @survey_answers.page(params[:page]).per(20)
  end

  def show
    @survey = @survey_answer.survey
  end

  def destroy
    @survey_answer.destroy!
    redirect_to survey_answers_path
  end

  def load_survey_answer
    @survey_answer  = SurveyAnswer.where(user_id: current_user.id, id: params[:id]).first

    if @survey_answer.blank?
      redirect_to survey_answers_path
    end
  end
end

app/views/survey_answers/_index_header.html.haml
%nav
  %ol.breadcrumb
    %li.breadcrumb-item
      .fa.fa-file
      My Surveys
    %li.ml-auto
      = link_to "#", id: "btn-new" do
        .fa.fa-plus
        New Answer

app/views/survey_answers/_list.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th
        Survey
      %th
        Last Updated
      %th
        Status
  %tbody
    - @survey_answers.each do |o|
      %tr
        %td
          = link_to survey_answer_path(o) do
            #{o.survey}
        %td
          #{o.updated_at.strftime("%b %d, %Y")}
        %td
          - if o.is_final
            .badge.badge-success
              Submitted
          - else
            .badge.badge-danger
              Unsubmitted

app/views/survey_answers/_show_header.html.haml
%nav
  %ol.breadcrumb
    %li.breadcrumb-item
      = link_to survey_answers_path do
        .fa.fa-file
        My Surveys
    %li.breadcrumb-item
      .fa.fa-check
      Answering Survey #{@survey_answer.survey}

app/views/survey_answers/index.html.haml
= render partial: "index_header"

.container-fluid
  .row
    .col
      - if @survey_answers.size > 0
        = render partial: "list"
        = paginate @survey_answers
      - else
        %p
          No survey answers yet.

= render partial: "survey_answers/modals/new"

= javascript_include_tag "survey_answers/Index.js"

:javascript
  $(document).ready(function() {
    var authenticityToken = $("meta[name='csrf-token']").attr('content');

    Index.init({
      authenticityToken: authenticityToken
    });
  });

app/views/survey_answers/show.html.haml
= render partial: "show_header"

.container-fluid
  .row
    .col
      %h2
        #{@survey}
      %hr
      - @survey_answer.survey_question_answers.each do |o|
        .card
          .card-body
            %h5
              #{o.question.content}
            %hr
            - if o.question.question_type == "single"
              - if !@survey_answer.is_final
                - o.question.question_options.order("priority ASC").each do |option|
                  = radio_button_tag("options-#{o.question.id}", option.val, option.val == o.answer, class: "radio-selection", data: { val: "#{option.val}", target: "#answer-#{o.id}" })
                  #{option.label}
                  %br
                = hidden_field_tag :answer, o.answer, class: "form-control answer", id: "answer-#{o.id}", data: { id: o.id }
                %hr
                .btn.btn-info.btn-block.btn-submit{ data: { id: o.id, target: "#answer-#{o.id}" } }
                  .fa.fa-check
                  Save Answer
              - else
                %ul
                  - o.question.question_options.order("priority ASC").each do |option|
                    %li
                      #{option.label}
                #{o.answer}
            - elsif o.question.question_type == "multiple"
              - if !@survey_answer.is_final
                - o.question.question_options.order("priority ASC").each do |option|
                  = check_box_tag("option-#{option.id}", option.val, o.answer.split(",").include?(option.val), class: "check-box-selection cb-group-#{o.question.id}", data: { val: "#{option.val}", target: "#answer-#{o.id}", group_target: ".cb-group-#{o.question.id}" })
                  #{option.label}
                  %br
                = hidden_field_tag :answer, o.answer, class: "form-control answer", id: "answer-#{o.id}", data: { id: o.id }
                %hr
                .btn.btn-info.btn-block.btn-submit{ data: { id: o.id, target: "#answer-#{o.id}" } }
                  .fa.fa-check
                  Save Answer
              - else
                #{o.answer}
            - elsif o.question.question_type == "single-written"
              - if !@survey_answer.is_final
                = text_field_tag :answer, o.answer, class: "form-control answer", id: "answer-#{o.id}", data: { id: o.id }
                %hr
                .btn.btn-info.btn-block.btn-submit{ data: { id: o.id, target: "#answer-#{o.id}" } }
                  .fa.fa-check
                  Save Answer
              - else
                #{o.answer}
            - elsif o.question.question_type == "date"
              - if !@survey_answer.is_final
                = text_field_tag :answer, o.answer, class: "form-control answer", type: "date", id: "answer-#{o.id}", data: { id: o.id }
                %hr
                .btn.btn-info.btn-block.btn-submit{ data: { id: o.id, target: "#answer-#{o.id}" } }
                  .fa.fa-check
                  Save Answer
              - else
                #{o.answer}
            - elsif o.question.question_type == "numeric"
              - if !@survey_answer.is_final
                = text_field_tag :answer, o.answer, class: "form-control answer", type: "number", id: "answer-#{o.id}", data: { id: o.id }
                %hr
                .btn.btn-info.btn-block.btn-submit{ data: { id: o.id, target: "#answer-#{o.id}" } }
                  .fa.fa-check
                  Save Answer
              - else
                #{o.answer}
        %hr
      - if @survey_answer.is_final
        %p
          This survey has already been answered
      - else
        #btn-finalize.btn.btn-success.btn-block{ data: { id: @survey_answer.id } }
          .fa.fa-check
          Finalize
        %hr
        .card.text-white.bg-info
          .card-header
            Delete Record
          .card-body
            %h5
              Warning!
            %p
              Once you delete this record, this action cannot be undone. 
            .pull-right
              = link_to survey_answer_path(@survey_answer), class: 'btn btn-danger', method: :delete, data: { confirm: "Are you sure?" } do |o|
                .fa.fa-times
                Confirm Delete
        %hr

= render partial: "survey_answers/modals/finalize"

= javascript_include_tag "survey_answers/Show.js"

:javascript
  $(document).ready(function() {
    var authenticityToken = $("meta[name='csrf-token']").attr('content');

    Show.init({
      authenticityToken: authenticityToken
    });
  });