config/routes.rb
Rails.application.routes.draw do
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get 'login', to: 'pages#login', as: :new_user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: "pages#index"
  get "/profile", to: "pages#profile", as: :profile
  get "/register", to: "pages#register", as: :register
  get "/confirm/:confirmation_token", to: "pages#confirm", as: :confirm
  get "/resend_confirmation", to: "pages#resend_confirmation", as: :resend_confirmation

  resources :patients
  resources :establishments
  resources :survey_answers, only: [:index, :show, :destroy]

  draw :administration
  draw :api
end

app/views/shared/_errors.html.erb
<script id="errors-template" type="x-tmpl-mustache">
  <div class="card border-danger">
    <div class="card-body text-danger">
      <h5 class="card-title">Some Errors Occurred</h5>
      <ul>
        {{#errors}}
          <li>{{.}}</li>
        {{/errors}}
      </ul>
    </div>
  </div>
</script>

app/views/shared/_login.html.haml
- if !user_signed_in?
  .input-group-prepend
    %span.input-group-text
      @
    = text_field_tag :email, "", id: 'input-email', class: 'form-control', placeholder: 'Email / Username'
  .input-group-prepend
    %span.input-group-text
      .fa.fa-lock
    = password_field_tag :password, "", id: 'input-password', class: 'form-control', placeholder: 'Password'
  #btn-login.btn.btn-info
    .fa.fa-upload
    Login
  = link_to register_path, class: "btn btn-info" do
    .fa.fa-check
    Register

app/views/shared/_nav.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-info
  = link_to root_path, class: "navbar-brand" do
    Covid19 Response Hub
  %button.navbar-toggler{ data: { toggle: "collapse", target: "#navbar-nav" } }
    %span.navbar-toggler-icon
  #navbar-nav.collapse.navbar-collapse
    %ul.navbar-nav
      - if user_signed_in?
        - if current_user.is_active
          %li.nav-item
            = link_to patients_path, class: 'nav-link' do
              .fa.fa-users
              My Records
          %li.nav-item
            = link_to establishments_path, class: 'nav-link' do
              .fa.fa-building
              My Establishments
          %li.nav-item
            = link_to survey_answers_path, class: 'nav-link' do
              .fa.fa-file
              My Surveys
        %li.nav-item
          = link_to profile_path, class: 'nav-link' do
            .fa.fa-user
            Profile
        - if current_user.admin?
          %li.nav-item
            = link_to administration_surveys_path, class: 'nav-link' do
              .fa.fa-file
              Surveys
          %li.nav-item
            = link_to administration_users_path, class: 'nav-link' do
              .fa.fa-users
              Users
        %li.nav-item
          = link_to destroy_user_session_path, method: :delete, class: 'nav-link' do
            .fa.fa-times
            Logout
  = render partial: "shared/login"