config/routes.rb
Rails.application.routes.draw do
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get 'login', to: 'pages#login', as: :new_user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root to: "pages#index"
  get "/profile", to: "pages#profile", as: :profile
  get "/register", to: "pages#register", as: :register
  get "/confirm/:confirmation_token", to: "pages#confirm", as: :confirm
  get "/resend_confirmation", to: "pages#resend_confirmation", as: :resend_confirmation

  resources :patients
  resources :establishments
  resources :survey_answers, only: [:index, :show, :destroy]

  draw :administration
  draw :api
end

app/models/establishment.rb
class Establishment < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :number_of_people_in_need, presence: true
  validates :contact_person, presence: true
  validates :address, presence: true
  validates :contact_number, presence: true
  validates :region, presence: true
  validates :province, presence: true
  validates :city, presence: true
  validates :village, presence: true

  serialize :needs, Array

  def to_s
    name
  end
end

app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_active!
  before_action :load_establishment, only: [:edit, :update, :destroy, :show]
  before_action :load_values, only: [:new, :create, :edit, :update]

  def index
    @establishments = Establishment.where(user_id: current_user.id)

    @establishments = @establishments.order(
                  "updated_at DESC"
                )

    @establishments = @establishments.page(params[:page]).per(20)
  end

  def show
  end

  def new
    @establishment  = Establishment.new
  end

  def create
    @establishment      = Establishment.new(establishment_params)
    @establishment.user = current_user

    if @establishment.save
      redirect_to establishment_path(@establishment)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @establishment.update(establishment_params)
      redirect_to establishment_path(@establishment)
    else
      render :edit
    end
  end

  def destroy
    @establishment.destroy!
    redirect_to establishments_path
  end

  def load_values
    cmd = FetchRegions.new
    cmd.execute!

    @data = cmd.data
  end

  def load_establishment
    @establishment  = Establishment.where(user_id: current_user.id, id: params[:id]).first

    if @establishment.blank?
      redirect_to establishments_path
    end
  end

  def establishment_params
    params.require(:establishment).permit!
  end
end

app/views/establishments/_edit_header.html.haml
%nav
  %ol.breadcrumb
    %li.breadcrumb-item
      = link_to establishments_path do
        .fa.fa-building
        My Establishments
    %li.breadcrumb-item
      .fa.fa-pencil-alt
      Edit Record #{@establishment}

app/views/establishments/_form.html.haml
= simple_form_for @establishment do |f|
  .row
    .col
      .form-group
        = f.input :name, label: 'Name of Establishment', input_html: { class: 'form-control' }
      .form-group
        = f.input :contact_person, input_html: { class: 'form-control' }
      .form-group
        = f.input :contact_number, input_html: { class: 'form-control' }
      .form-group
        = f.input :address, input_html: { class: 'form-control' }
  .row
    .col-md-3
      .form-group
        = f.input :region, as: :select, collection: [], input_html: { id: 'select-region', class: 'form-control' }
    .col-md-3
      .form-group
        = f.input :province, as: :select, collection: [], input_html: { id: 'select-province', class: 'form-control' }
    .col-md-3
      .form-group
        = f.input :city, as: :select, collection: [], input_html: { id: 'select-city', class: 'form-control' }, label: "City / Municipality"
    .col-md-3
      .form-group
        = f.input :village, as: :select, collection: [], label: "Barangay", input_html: { id: 'select-village', class: 'form-control' }
  .row
    .col-md-3
      .form-group
        = f.input :number_of_people_in_need, input_html: { class: 'form-control' }
    .col-md-3
      .form-group
        %label
          * Needs
        = f.input :needs, as: :check_boxes, collection: Patient::NEEDS, label: false
    .col-md-3
      .form-group
        %label
          * Severity
        = f.input :severity, as: :select, collection: Patient::NEEDS_STATUS, label: false, input_html: { class: 'form-control' }
  %hr
  .row
    .col
      %button{ type: "submit", class: "btn btn-info" }
        .fa.fa-check
        Save
      = link_to establishments_path, class: "btn btn-danger" do
        .fa.fa-times
        Cancel

#parameters{ data: { data: @data.to_json, region: @establishment.region, province: @establishment.province, city: @establishment.city, village: @establishment.village } }
= javascript_include_tag "establishments/Form.js"

:javascript
  $(document).ready(function() {
    var $parameters = $("#parameters");
    var data        = $parameters.data('data');
    var region      = $parameters.data('region');
    var province    = $parameters.data('province');
    var city        = $parameters.data('city');
    var village     = $parameters.data('village');

    Form.init({
      data: data,
      region: region,
      province: province,
      city: city,
      village: village
    });
  });

app/views/establishments/_index_header.html.haml
%nav
  %ol.breadcrumb
    %li.breadcrumb-item
      .fa.fa-building
      My Establishment Posts
    %li.ml-auto
      = link_to new_establishment_path do
        .fa.fa-plus
        New Record

app/views/establishments/_index_list.html.haml
%div.table-responsive
  %table.table.table-bordered.table.table-sm
    %thead
      %tr
        %th
          Name
        %th
          Contact Person
        %th
          Contact Number
        %th
          Address
        %th
          Needs
        %th
          Severity
        %th
          Last Updated
        %th.text-center
          Actions
    %tbody
      - @establishments.each do |o|
        %tr
          %td
            #{o.name}
          %td
            #{o.contact_person}
          %td
            #{o.contact_number}
          %td
            #{o.address}
          %td
            - if o.needs.present?
              %ul
                - o.needs.select{ |o| o.present? }.each do |s|
                  %li
                    #{s}
          %td
            - if o.severity == "manageable"
              .badge.badge-info
                Manageable
            - elsif o.severity == "critical"
              .badge.badge-danger
                Critical
          %td
            #{o.updated_at.strftime("%b %d, %Y")}
          %td.text-center
            = link_to establishment_path(o) do
              .fa.fa-search

app/views/establishments/_new_header.html.haml
%nav
  %ol.breadcrumb
    %li.breadcrumb-item
      = link_to establishments_path do
        .fa.fa-building
        My Establishments
    %li.breadcrumb-item
      .fa.fa-plus
      New Record

app/views/establishments/_show_header.html.haml
%nav
  %ol.breadcrumb
    %li.breadcrumb-item
      = link_to establishments_path do
        .fa.fa-establishments
        My Establishments
    %li.breadcrumb-item
      .fa.fa-user
      #{@establishment}
    %li.ml-auto
      = link_to edit_establishment_path(@establishment)  do |o|
        .fa.fa-pencil-alt
        Edit Record

app/views/establishments/edit.html.haml
= render partial: "edit_header"

.container-fluid
  .row
    .col
      .card
        .card-body
          = render partial: "form"

app/views/establishments/index.html.haml
= render partial: "index_header"
.container-fluid
  .row
    .col
      - if @establishments.size > 0
        = render partial: "index_list"
        = paginate @establishments
      - else
        %p
          No establishments yet.

app/views/establishments/new.html.haml
= render partial: "new_header"

.container-fluid
  .row
    .col
      %h3
        New Establishment Form
      .card
        .card-body
          = render partial: "form"

app/views/establishments/show.html.haml
= render partial: "show_header"
.container-fluid
  %h3.text-muted
    #{@establishment}
  .row
    .col-md-12
      %table.table.table-bordered.table-sm
        %tbody
          %tr
            %th
              Contact Number
            %td
              #{@establishment.contact_number}
          %tr
            %th
              Address
            %td
              #{@establishment.address}
          %tr
            %th
              Region
            %td
              #{@establishment.region}
          %tr
            %th
              Province
            %td
              #{@establishment.province}
          %tr
            %th
              City / Municipality
            %td
              #{@establishment.city}
          %tr
            %th
              Village / Barangay
            %td
              #{@establishment.village}
          %tr
            %th
              Number of People in Need
            %td
              #{@establishment.number_of_people_in_need}
          %tr
            %th
              Needs
            %td
              %ul
                - @establishment.needs.select{ |o| o.present? }.each do |o|
                  %li
                    #{o}
              - if @establishment.severity == "manageable"
                .badge.badge-info
                  Manageable
              - elsif @establishment.severity == "critical"
                .badge.badge-danger
                  Critical
      %hr
      .card.text-white.bg-info
        .card-header
          Delete Record
        .card-body
          %h5
            Warning!
          %p
            Once you delete this record, this action cannot be undone. 
          .pull-right
            = link_to establishment_path(@establishment), class: 'btn btn-danger', method: :delete, data: { confirm: "Are you sure?" } do |o|
              .fa.fa-times
              Confirm Delete
      %hr